"""Check exact tool specs that LangChain generates for our actual tools."""
import os
os.chdir(r'd:\python study\ai_coding\academic-rag-agent')
from dotenv import load_dotenv; from pathlib import Path
load_dotenv(Path('.env'))

import json
from src.rag.vector_store import VectorStoreManager
from src.tools.arxiv_tool import arxiv_search_tool
from langchain_core.tools import create_retriever_tool
from langchain_core.utils.function_calling import convert_to_openai_tool

vs = VectorStoreManager('./vector_store', 'BAAI/bge-small-en-v1.5')
retriever = vs.get_retriever(4)
retriever_tool = create_retriever_tool(
    retriever=retriever,
    name="search_uploaded_papers",
    description="Search across locally indexed PDFs and arXiv paper abstracts via Hybrid BM25+FAISS+RRF retrieval."
)
tools = [retriever_tool, arxiv_search_tool]

print("=== Tool specs generated by LangChain ===")
all_specs = []
for t in tools:
    spec = convert_to_openai_tool(t)
    spec_json = json.dumps(spec, ensure_ascii=False)
    print(f"\nTool: {t.name}")
    print(f"  JSON length: {len(spec_json)}")
    # Scan for surrogates
    surrs = [(i, c, f"U+{ord(c):04X}") for i, c in enumerate(spec_json) if 0xD800 <= ord(c) <= 0xDFFF]
    if surrs:
        print(f"  SURROGATES FOUND: {surrs[:3]}")
    else:
        print(f"  Clean (no surrogates)")
    all_specs.append(spec)

print(f"\n=== Full request payload scan ===")
from src.agent.agent import SYSTEM_PROMPT
payload = {
    "model": os.getenv('OPENAI_MODEL'),
    "temperature": 0,
    "stream": False,
    "tools": [{"type":"function","function": s['function']} for s in all_specs],
    "messages": [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": "你好，请用中文介绍你自己的功能"}
    ],
}
full_json = json.dumps(payload, ensure_ascii=False)
print(f"Total payload JSON length: {len(full_json)}")
surrs = [(i, c, f"U+{ord(c):04X}") for i, c in enumerate(full_json) if 0xD800 <= ord(c) <= 0xDFFF]
if surrs:
    for pos, c, code in surrs[:5]:
        print(f"SURROGATE at {pos}: {code}")
        print(f"Context: {repr(full_json[max(0,pos-40):pos+40])}")
else:
    print("Full payload is CLEAN (no surrogates in static content)")
    print("Surrogate must come from LangChain's internal message formatting at runtime")
    
# Now try to encode (same as SDK does)
try:
    encoded = full_json.encode('utf-8')
    print(f"Encoding OK: {len(encoded)} bytes")
except UnicodeEncodeError as e:
    print(f"Encode failed at {e.start}: {repr(full_json[e.start-5:e.start+5])}")
